### ISSUE TITLE
Linux CI builds failing.

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/pytng-feedstock#1]
@orbeckst  The linux CI builds seem to be failing and I couldn't really make head or tail of it.

**Comment by orbeckst** [comment]
Can you point me to something to look at ,please?

**Comment by orbeckst** [comment]
I don't know the build infrastructure so I don't know what the error

    ValueError: Variant configuration errors in /home/conda/feedstock_root/.ci_support/linux_64_python3.6.____cpython.yaml:
      zip fields in zip_key group ('cdt_name', 'docker_image') are not all the same length

really means. (And it appears for all Linux versions.)

There was a complaint that we didn't define the numpy version and that it defaulted to 1.11.

       WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

Sorry to ping you @ocefpaf , but it's not clear to us where the error comes from. (If there's a more general GitHub handle we should ping for help then please let us know.) Thanks in advance.

**Comment by ocefpaf** [comment]
No problem. That was a minor glitch in our re-rendering system. Merging #3 should fix it.

**Comment by hmacdope** [comment]
I'll approve and merge #3 once CI completes.
