### ISSUE TITLE
follow CFEP05 for numbering pre-release

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/pytng-feedstock#2]
Given the comment https://github.com/conda-forge/staged-recipes/pull/12917#discussion_r508420579 we should follow https://github.com/conda-forge/cfep/blob/master/cfep-05.md to number our pre-releases.

Alternatively, if we're ready for a regular release https://github.com/MDAnalysis/pytng/issues/5 (0.2.2 ?) then we could just move on to that one.

**Comment by hmacdope** [comment]
I think best to cut a proper release @ 0.2.2?

**Comment by orbeckst** [comment]
Yes, there are no show-stoppers, right?

**Comment by hmacdope** [comment]
No show-stoppers as far as I am concerned :)
